runtime: python312

handlers:
- url: /ESC
  static_dir: ESC-Rankings

- url: /NFs
  static_dir: NF-Rankings

- url: /Other
  static_dir: Other-Rankings

- url: /Ideal
  static_dir: Ideal-Rankings


- url: /static
  static_dir: static